---
title: "p8105_hw3_jh4617"
author: "Junjie Hu"
date: "2023-10-12"
output: github_document
editor_options: 
  chunk_output_type: inline
---

```{r load data }
library(p8105.datasets)
library(tidyverse)
data("instacart")
```

```{r echo = FALSE}
instacart

names(instacart)
```

There are `r length(unique(pull(instacart, aisle)))` aisles. The `r mode(pull(instacart, aisle))` aisle is the most items ordered from.

```{r plot item}
instacart |>
  group_by(aisle) |>
  summarize(sum_order_number = sum(order_number)) |>

  filter(sum_order_number > 10000) |>
  arrange(sum_order_number) |>
  ggplot(aes(x = aisle, y = sum_order_number)) +
  geom_boxplot() +
    labs(
    title = "The number of items ordered in each aisle",
    x = "Aisle",
    y = "Number") 

  mutate(sum_order_number = min_rank(desc(sum_order_number))) |>
```

```{r}
instacart |>
  group_by(aisle, product_name) |>
  summarize(n_obs = n()) |>
  arrange(aisle, desc(n_obs)) |>
  top_n(3, n_obs)
```

```{r}
instacart |>
  group_by(product_name, order_dow) |>
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) |>
  summarize(mean_order_hour_of_day = mean(order_hour_of_day)) |>
  mutate(order_dow = recode(order_dow, "0" = "sunday",
                            "1" = "monday",
                            "2" = "tuesday",
                            "3" = "wednesday",
                            "4" = "thursday",
                            "5" = "friday",
                            "6" = "saturday"))|>
  pivot_wider(
    names_from = order_dow,
    values_from = mean_order_hour_of_day
  )
```

# problem 2

```{r echo = FALSE}
library(p8105.datasets)
data("brfss_smart2010")

brfss_smart2010
names(brfss_smart2010)
```

data cleaning
```{r}
problem2 = 
  brfss_smart2010 |> 
  janitor::clean_names() |>
  filter(topic == "Overall Health",
         response %in% c("Excellent", "Poor")) |>
  mutate(response = factor(response, levels = c("Poor", "Excellent"))) 
```


2002
```{r}
problem2_2002 =
  problem2 |>
  group_by(locationabbr) |>
  filter(year == "2002") |>
  summarize(n_obs = n() / 2) |>
  filter(n_obs >= 7)
print(problem2_2002)
```
In 2002, there are 6 states were observed at 7 or more locations. Those states are CT, FL, MA, NC, NJ, PA.


2010
```{r}
problem2_2010 =
  problem2 |>
  group_by(locationabbr) |>
  filter(year == "2010") |>
  summarize(n_obs = n() / 2) |>
  filter(n_obs >= 7)
print(problem2_2010)
```
In 2010, there are 14 states were observed at 7 or more locations. Those states are CA, CO, FL, MA, MD, NC, NE, NJ, NY, OH, PA, SC, TX, WA.


```{r}
problem2_ggplot = 
  problem2 |>
  filter(response == "Excellent") |> 
  group_by(locationabbr) |>
  mutate(mean_data_value = mean(data_value, na.rm = TRUE)) |>
  select(year, locationabbr, mean_data_value)

ggplot(data = problem2_ggplot, aes( x = locationabbr, y = mean_data_value, group = 1)) +
  geom_point() +
  geom_line() +
   labs(x = "Location Abbreviation", 
        y = "Mean Data Value", 
        title = "Mean Data Value for Excellent Response by Location")
```



